//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Orders.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Datakini.Framework;
    using InventorySystem.Orders.Entities;
    
    public partial class InventorySystemOrderContext : DbContext
    {
       const string commonName = "InventorySystem";
    static readonly string connstr = EntityConnectionHelper.CommonEFConnString("InventorySystemOrderModel",commonName);
        public InventorySystemOrderContext()
            : base(connstr)
    {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Pattern> Pattern { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductGroup> ProductGroup { get; set; }
        public DbSet<SalesOrder> SalesOrder { get; set; }
        public DbSet<SalesOrderDetail> SalesOrderDetail { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
    }
}
